services:
  - type: web
    name: qa365-app
    env: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_NAME
        value: "QA365"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://qa365-app.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
